### ISSUE TITLE
Sort staff records using GridFieldSortableRows?

### ISSUE THREAD

**Issue by luminousmg** [andrewhoule/silverstripe-staffpage#4]
Hello,

I have been using your plugin but I would like the ability to "Click and drag" sort the records using GridFieldSortableRows.

Is this possible with the StaffPage module?

Thanks!

**Comment by luminousmg** [comment]
Answered my own question lol.  Just found the how-to in the SortableGridField docs for ModelAdmin
https://github.com/UndefinedOffset/SortableGridField/blob/master/docs/ModelAdminExample.md

**Comment by luminousmg** [comment]
Added the following code snippet in code/StaffAdmin.php to the GetEditForm function at line 31:

before:

`public function getEditForm($id = null, $fields = null)
    {
        $form=parent::getEditForm($id, $fields);
        if ($this->modelClass=='Staff' && $gridField=$form->Fields()->dataFieldByName($this->sanitiseClassName($this->modelClass))) {
        }
        return $form;
    }`

After: 

`public function getEditForm($id = null, $fields = null)
    {
        $form=parent::getEditForm($id, $fields);
        if ($this->modelClass=='Staff' && $gridField=$form->Fields()->dataFieldByName($this->sanitiseClassName($this->modelClass))) {

```
    }
     if($gridField instanceof GridField) {
            $gridField->getConfig()->addComponent(new GridFieldSortableRows('SortOrder'));
      }
    return $form;
}`
```

**Comment by andrewhoule** [comment]
Ah, good call. I added that to the master branch.
